### PR TITLE
Reduce directory changing

### PR DESCRIPTION
**Pull request by shayne-fletcher**
> Why do we change into that directory so many times instead of staying just there. Let's simplify this in a separate PR.

Follow up on https://github.com/digital-asset/davl/pull/192

### CODE REVIEW

**Comment by shayne-fletcher** [comment]
> That works. Thanks.
> 
> Why are you afraid of a simple `cd upgrade-v4-v5-automation` or `pushd upgrade-v4-v5-automation` somewhere close to the top of the file and dropping all the `&&` chaining. The `set -e` already ensures that the script fails _immediately_ as soon as one command in it fails.

Well, my reasoning is, and I may be wrong about it is, if it fails, it fails in a subshell so regardless of the exit status of the script, the current working directory will not be modified.

That said will simplify with `pushd` and `popd` at the end.

**Comment by shayne-fletcher** [comment]
@hurryabit This more to your liking?

**Comment by hurryabit** [comment]
That is really great. Thanks.

**Comment by shayne-fletcher** [comment]
Awesome. Thanks Martin. See you tomorrow!

**Pull request merged**
