### PR TITLE
v4 together with upgrade path

### PR DESCRIPTION
**Pull request by robin-da**
This is v4 of davl, together with an upgrade project in the same SDK. There's a couple of things that don't work yet because of a bug in the data dependency imports, which leads to references to DA.Internal.LF data types not properly replaced to the current sdk. The following doesn't work
 - tests (I tested manually)
 - filtering by party in trigger 
- cross sdk upgrade

We only have one trigger for one template (that currently doesn't seem to work).

### CODE REVIEW

**Comment by robin-da** [comment]
cross sdk upgrade also works with my latest patch to master

**Comment by garyverhaegen-da** [comment]
Should this get updated to 0.13.38? I imagine that must include the fixes in HEAD that this branch was using? If so, does that mean we can upgrade the runtime SDK in production too now?

**Comment by robin-da** [comment]
@garyverhaegen-da Hi Gary, yes this will be on 0.13.38 since I'm testing on HEAD. I guess we'll upgrade the runtime SDK in production as soon as this is ready, this is still WIP, and @hurryabit has a different idea for the ugprade model.

**Comment by hurryabit** [comment]
This is not relevant anymore since we've already upgraded to v4.

**Pull request closed without merging**
