### PR TITLE
fix permissions (for real this time)

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Maybe.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Also took the opportunity to record the fact that I've set all the counts to 0, effectively shutting down the system.

**Comment by garyverhaegen-da** [comment]
Oh and speaking of recording: I have manually deleted all of the DB backups post-1.18-rc2 upgrade, because there is no 1.18-rc2 -> 1.18-rc3 upgrade path. This way when we deploy 1.17.2 again we'll get a working database and then we can upgrade to 1.18-rc3.

**Review by realvictorprm — APPROVED** [review]

**Comment by stefanobaghino-da** [comment]
What was the issue?

**Comment by garyverhaegen-da** [comment]
This repo has CI deploying things, which means the machine running CI needs to have some permissions (but ideally not too many). The `permissions` folder is meant to be run by an admin who has full access and set up the permissions for the CI machine.

The `infra` folder is meant to be run by CI, but can also be run by anyone who has at least as many rights as CI.

Since I'm an admin, that makes it hard for me to locally test that things are split correctly between the two. I'd put some of the things that require  admin rights into the `infra` module instead of the `permissions` module, so CI failed to run. But CI only tries to run that bit on main builds for releases, so it took a bit of time before the issue manifested.

**Pull request merged**
